import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

function soma() {
  const horaUm = document.getElementById("h1").value;
  const horaDois = document.getElementById("h2").value;
  var somaHoras = Number(horaUm) + Number(horaDois);

  const minutoUm = document.getElementById("m1").value;
  const minutoDois = document.getElementById("m2").value;
  var somaMinutos = Number(minutoUm) + Number(minutoDois);

  while (somaMinutos >= 60) {
    somaMinutos = somaMinutos - 60;
    somaHoras = somaHoras + 1;
  }

  console.log(somaHoras);
  console.log(somaMinutos);
}

function subtrai() {
  const horaUm = document.getElementById("h1").value;
  const horaDois = document.getElementById("h2").value;
  var diminuiHoras = Number(horaUm) - Number(horaDois);
  diminuiHoras = Math.abs(diminuiHoras)
  console.log(diminuiHoras)

  const minutoUm = document.getElementById("m1").value;
  const minutoDois = document.getElementById("m2").value;
  var diminuiMinutos = Number(minutoUm) - Number(minutoDois);

  while (diminuiMinutos >= 60 || diminuiMinutos <= -1) {
    if (diminuiMinutos <= -1) {
      diminuiMinutos = diminuiMinutos * -1;
      diminuiHoras = diminuiHoras - 1;
    } else {
      diminuiMinutos = diminuiMinutos - 60;
      diminuiHoras = diminuiHoras + 1;
    }
  }

  console.log(Math.abs(diminuiHoras));
  console.log(diminuiMinutos);
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className=" text-white">oii</p>
        <div className=" space-x-2 mb-2">
          <input id="h1" placeholder="hora" type="number"></input>
          <input id="m1" placeholder="minuto" type="number"></input>
        </div>
        <div className=" space-x-2">
          <input id="h2" placeholder="hora" type="number"></input>
          <input id="m2" placeholder="minuto" type="number"></input>
        </div>
        <div className=" mt-2  space-x-2 ">
          <button onClick={soma} className=" bg-white">
            Somar
          </button>
          <button onClick={subtrai} className=" bg-white">
            Subtrair
          </button>
        </div>
      </main>
    </>
  );
}
