import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

function soma() {
  const horaUm = document.getElementById("h1").value;
  const horaDois = document.getElementById("h2").value;
  var somaHoras = Number(horaUm) + Number(horaDois);

  const minutoUm = document.getElementById("m1").value;
  const minutoDois = document.getElementById("m2").value;
  var somaMinutos = Number(minutoUm) + Number(minutoDois);

  while (somaMinutos >= 60) {
    somaMinutos = somaMinutos - 60;
    somaHoras = somaHoras + 1;
  }

  console.log(somaHoras);
  console.log(somaMinutos);
}

function subtrai() {
  let horaUm = document.getElementById("h1").value;
  let horaDois = document.getElementById("h2").value;
  let minutoUm = document.getElementById("m1").value;
  let minutoDois = document.getElementById("m2").value;

  horaUm = Number(horaUm);
  minutoUm = Number(minutoUm);
  horaDois = Number(horaDois);
  minutoDois = Number(minutoDois);

  while (horaUm > 0) {
    minutoUm += 60;
    horaUm--;
  }

  while (horaDois > 0) {
    horaDois--;
    minutoDois += 60;
  }

  let rh = 0;
  let rm = minutoUm - minutoDois;

  if (minutoDois > minutoUm) {
    rm = minutoDois - minutoUm;
  }

  while (rm > 59) {
    rh++;
    rm -= 60;
  }

  console.log(rh);
  console.log(rm);
}

export default function Home() {
  const [rh, setRh] = useState("");

  const resultado = () => {
    setRh(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-white" onChange={() => resultado()}>
          oi{rh}
        </p>
        <div className=" space-x-2 mb-2">
          <input id="h1" placeholder="hora" type="number"></input>
          <input id="m1" placeholder="minuto" type="number"></input>
        </div>
        <div className=" space-x-2">
          <input id="h2" placeholder="hora" type="number"></input>
          <input id="m2" placeholder="minuto" type="number"></input>
        </div>
        <div className=" mt-2  space-x-2 ">
          <button onClick={soma} className=" bg-white">
            Somar
          </button>
          <button onClick={subtrai} className=" bg-white">
            Subtrair
          </button>
        </div>
      </main>
    </>
  );
}
